parties: # parties default id
  guest:
    - 1111
  host:
    - 2222
    - 3333
    - 4444
    - 5555
  arbiter:
    - 1001

backend: 0 # 0 for eggroll, or 1 for spark with rabbitmq, 2 for spark with pulsar

work_mode: 0 # 0 for standalone, or 1 for cluster

data_base_dir: "/data/projects/fate" # path to project base where data is located